stages:
  preprocess:
    cmd: python -m src.preprocess
    deps:
      - src/preprocess.py
      - data/raw/train.parquet
    outs:
      - data/processed/train_ready.parquet

  tune:
    cmd: python -m src.tune
    deps:
      - src/tune.py
      - src/data_loader.py
      - configs/config.py
      - data/processed/train_ready.parquet

  train:
    cmd: python -m src.train
    deps:
      - src/train.py
      - src/data_loader.py
      - configs/config.py
      - configs/params.yaml
      - data/processed/train_ready.parquet
    params:
      - configs/params.yaml:
        - xgboost_params
        - train