data:
  raw_path: Data/Raw/train.parquet
  processed_path: Data/Processed/train_ready.parquet
  test_size: 0.2
  random_state: 42
train:
  num_boost_round: 1000
  early_stopping_rounds: 30
xgboost_params:
  objective: binary:logistic
  tree_method: hist
  eval_metric: aucpr
  scale_pos_weight: 1.616260902034584
  subsample: 0.8082412745026589
  colsample_bytree: 0.7196942522110269
  max_depth: 10
  learning_rate: 0.10856617515801444
  gamma: 1.6739268678611028
optuna:
  n_trials: 100
  learning_rate_min: 0.01
  learning_rate_max: 0.3
  max_depth_min: 3
  max_depth_max: 10
  subsample_min: 0.5
  subsample_max: 1.0
  colsample_bytree_min: 0.5
  colsample_bytree_max: 1.0
  gamma_min: 0.0
  gamma_max: 5.0
  scale_pos_weight_min: 1.0
  scale_pos_weight_max: 10.0
